package com.estuate.mpreplica.enums;


public enum NotificationType {
    // Module 2
    IDME_ACTION_REQUIRED,
    IDME_APPROVED_PENDING_LMS,
    IDME_DECLINED,
    LMS_INVITATION,
    LMS_COMPLETED_SELLER_ACTIVE,
    LMS_FAILED,
    SELLER_STATUS_MANUALLY_UPDATED,

    // Module 4 & 5: Order Related
    NEW_ORDER_ITEMS_FOR_SELLER,
    ORDER_ITEM_CONFIRMED_BY_SELLER_TO_CUSTOMER,
    ORDER_STATUS_UPDATE_TO_CUSTOMER,
    ORDER_ITEM_SHIPPED_TO_CUSTOMER,
    ORDER_FULLY_SHIPPED_TO_CUSTOMER,
    ORDER_DELIVERED_TO_CUSTOMER,
    ORDER_CANCELLED_TO_CUSTOMER,
    ORDER_PAYMENT_SUCCESSFUL_TO_CUSTOMER,
    ORDER_PAYMENT_FAILED_TO_CUSTOMER,
    ORDER_REQUIRES_OPERATOR_ATTENTION,

    GENERIC_NOTIFICATION
}

